---
layout: cv
title: Samuel Von's Resume
---
# Samuel Von Niederhausern

**City:** Rosenberg, TX | **Phone:** 1(817) 538-6243 | **Email:** sam.von@outlook.com

## Education
**Brigham Young University Idaho**, Rexburg, Idaho  
Bachelor of Science, Major in Geology, Certificate in GIS, GPA: 3.98  
Expected graduation: Spring 2026

## Work Experience
**Teaching Assistant**, BYUI — Rexburg, ID  
Jan 2024 – Present  
- Helped students with geology concepts such as Sedimentology and Stratigraphy  
- Maintained documentation of student grades  
- Assisted with field trips

**Tutor**, BYUI — Rexburg, ID  
Jan 2025 – Dec 2025  
- Created learning plans for students  
- Taught kinematics, physical geology, energy, circular motion

## Significant Coursework
- Historical Geology  
- Structure  
- Sedimentology and Stratigraphy  
- Igneous and Metamorphic Petrology  
- Geochemistry  
- GIS for STEM  
- Environmental Geology  
- Remote Sensing

## Extra Curricular Activities
**Logistics Helper**, Geology Society — Rexburg, ID  
Sep 2024 – Present  
- Organized events, recruited new members, assisted in planning 7 events  

**Student Research**, Rexburg, ID  
Jan 2025 – Apr 2025  
- Participated in research on Thin Films  
- Gained experience with XRD machine and vacuum chamber

## Significant Projects
- Cross-section of Canadian Fold and Thrust System  
- Mapping Stratigraphy of Richardson Amphitheater, UT  
- Statistical analysis of hazardous uranium mines in Navajo Nation using ArcGIS

<!-- ### Footer

Last updated: May 2013 -->